version: '3'
services:
    web:
        build:
            context: .
            args:
                HOST_DEV_USER: $HOST_DEV_USER
                HOST_DEV_UID: $HOST_DEV_UID
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app:/var/www
