version: '3'
services:
    web:
        build:
            context: .
            args:
                HOST_DEV_USER: $HOST_DEV_USER
                HOST_DEV_UID: $HOST_DEV_UID
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app:/var/www
        depends_on:
            - db
            - memorycache
    db:
        image: mariadb:10.5.8
        ports:
            - "3306:3306"
        volumes:
            - mariadb-lib:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: drupal
    memorycache:
        image: memcached:1.6-alpine
        ports:
            - "11211:11211"
        entrypoint:
            - "/entrypoint.sh"
            - "-m 128"
# Add mail service.

volumes:
    mariadb-lib:
